baseURL: "https://tamil.domesticatedonion.net"
languageCode: "en-us"
title: "Domesticated Onion"
theme: hugo-profile

Paginate: 3
disqusShortname: tamil-domesticatedonion-net
#googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: பதிவுகள்
      title: வலைப்பதிவுகள்
      url: /blogs
      weight: 1
    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: கட்டுரைகள்
      weight: 2
    - identifier: dropdown1
      title: science
      name: அறிவியல்
      url: /science
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: literature
      name: இலக்கியம்
      url: /literature
      parent: dropdown
      weight: 2
    - identifier: dropdown3
      title: humour
      name: நகைச்சுவை
      url: /humour
      parent: dropdown
      weight: 3
    - identifier: dropdown4
      title: music
      name: இசை
      url: /music
      parent: dropdown
      weight: 4
    - identifier: dropdown5
      title: sports
      name: விளையாட்டு
      url: /sports
      parent: dropdown
      weight: 5    
 
params:
  title: "உள்ளும் புறமும்"
  description: அண்டையின் நிகழ்வும், அகத்தின் தெறிப்பும்
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #menus:
  #     disableAbout: true
  #     disableExperience: true
  #  disableEducation: false
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  #Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "உங்கள் கருத்துகள் வரவேற்கப்படுகின்றன."
        school:
          name: ""
          url: ""
        date: ""
        GPA: ""
        content: |-
            - இத்தளத்தில் வெளியாகும் ஆக்கங்கள் குறித்த உங்கள் கருத்துகள் வரவேற்கப்படுகின்றன. உங்களுடைய பிற சமூக வலைத்தளங்கள் வழியாக நுழைவை உறுதி செய்தபின் நேரடியாகக் கருத்துகளை எழுதலாம். 
            - அடையாளம் காட்டாமல் பெயரிலியாகக் கருத்து எழுதுவதும் சாத்தியம். 
            - மேலதிக உதவிவிக்கு: 
  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com
